version: '3.4'

services:
 postgres:
   image: postgres:12
   container_name: db_mariage
   ports:
   - "5432:5432"
   restart: always
   volumes:
   - db_data:/var/lib/postgresql/data
   environment:
     POSTGRES_PASSWORD: root
     POSTGRES_DB: postgres
 hasura:
    image: hasura/graphql-engine:v2.12.0
    container_name: hasura
    ports:
    - "8080:8000"
    depends_on:
    - "postgres"
    restart: always
    environment:
        HASURA_GRAPHQL_METADATA_DATABASE_URL: postgres://postgres:root@postgres:5432/postgres
        HASURA_GRAPHQL_CONSOLE_ASSETS_DIR: "/srv/console-assets"
        HASURA_GRAPHQL_ENABLE_CONSOLE: "true"
        HASURA_GRAPHQL_DEV_MODE: "true"
        HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
        HASURA_GRAPHQL_ADMIN_SECRET: appmariage!
        HASURA_GRAPHQL_SERVER_PORT: 8000
        HASURA_BASE_ACTIONS_URL: http://host.docker.internal:5279

volumes:
  db_data: 